version: '3'

services:
    web:
        build: .
        command: python -u flask_brevets.py
        ports:
            - "6262:5000"
        depends_on:
            - brevetdb
        environment:
            MONGODB_HOSTNAME: brevetdb
    brevetdb:
        image: mongo:latest
